export const market = {
  id: 1,
  name: "BTC",
  symbol: "BTC",
  sizeDecimals: 5,
  priceDecimals: 2,
  markPrice: "60000",
  bidPrice: "59990",
  askPrice: "60010",
  openInterest: "0",
  dailyVolume: "0",
  fundingRate: "0",
  isOpen: true,
  observedAt: "2026-10-01T00:00:00Z",
};
export const markets = {
  network: "mainnet",
  chainId: 143,
  source: "PERPL_PUBLIC_API",
  sourceUrl: "https://perpl.xyz",
  receivedAt: "2026-10-01T00:00:00Z",
  observedAt: "2026-10-01T00:00:00Z",
  stale: false,
  markets: [market],
};
export const liquidity = {
  network: "mainnet",
  chainId: 143,
  marketId: 1,
  source: "PERPL_PUBLIC_API",
  sourceUrl: "https://perpl.xyz",
  receivedAt: "2026-10-01T00:00:00Z",
  observedAt: "2026-10-01T00:00:00Z",
  stale: false,
  sizeDecimals: 5,
  priceDecimals: 2,
  bids: [{ price: "59990", quantity: "1.2" }],
  asks: [{ price: "60010", quantity: "1.1" }],
  estimate: {
    requestedQuantity: "0.02",
    availableQuantity: "1.2",
    estimatedFilledQuantity: "0.02",
    estimatedAveragePrice: "59990",
    worstPrice: "59990",
    depthLimited: false,
    meaning: "Snapshot estimate only",
  },
};
export const activity = {
  status: "unavailable",
  source: "ENVIO",
  chainId: 143,
  watermark: null,
  receivedAt: "2026-10-01T00:00:00Z",
  events: [],
  error: "Envio pipeline not configured",
};
export const receipt = {
  schemaVersion: 1,
  id: "receipt-1",
  mode: "REPLAY",
  createdAt: "2026-10-01T00:00:00Z",
  scenario: "partial",
  authorization: {
    schemaVersion: 1,
    mode: "REPLAY",
    network: "mainnet",
    chainId: 143,
    accountId: "hypothetical-account",
    workerId: "replay-worker",
    marketId: 1,
    direction: "long",
    positionQuantity: "4000",
    authorizedCloseQuantity: "2000",
    priceLimit: "5999000",
    createdAt: "2026-10-01T00:00:00Z",
    requestDeadline: "2026-10-01T00:10:00Z",
    maxAttempts: 1,
  },
  authorizationDigest: "digest-approval",
  execution: {
    id: "execution-1",
    status: "PARTIAL",
    attemptedOperation: "REDUCE",
    providerWrites: 0,
    simulatedSubmissions: 1,
    filledQuantity: "1000",
    reservedQuantity: "1000",
    remainingPositionQuantity: "3000",
    timeline: [
      {
        title: "Partial observation",
        detail: "Only part of the close was observed",
        state: "pending",
      },
    ],
  },
  checks: [
    {
      name: "Close-only",
      result: "PASS",
      expected: "REDUCE",
      observed: "REDUCE",
      source: "REPLAY",
    },
  ],
  limitations: ["Simulated execution only"],
  integrity: {
    algorithm: "SHA-256",
    digest: "a".repeat(64),
    meaning: "Integrity does not prove execution",
  },
};
